### ISSUE TITLE
Support Parallelism

### ISSUE THREAD

**Issue by Kautenja** [Kautenja/nes-py#35]
### Is your feature request related to a problem? Please describe.

The gym environments don't support parallelism well using threading or same thread initialization.

### Describe the solution you'd like

A refactor of the C++ code to allow for better data containment and thus allow for multiple environments to run in the same thread.

### Describe alternatives you've considered

NA

### Additional context

multiprocessing works, but threading and same thread initialization fails.

**Comment by EliasHasle** [comment]
Hello! I was trying to run multiple gym-super-mario-bros environments in separate threads today, and it didn't work (Lots of "invalid OPcode"). Apparently, this is something you have been thinking about. I hope you will try to fix this. For my use case, multiple processes may be an option too, but my first choice was threading. Running multiple instances in a single thread is less interesting, as the main point is to use the power of multiple CPU cores. I am intending to use this for more efficient sampling of observations received through play with a given policy. I sample observations only with a low probability (dependent on the accumulated reward), so right now I believe the sampling is bound by the emulator, not by the harddrive. (And definitely not by the memory, if/when I move all operations into RAM).

**Comment by Kautenja** [comment]
Sharing data will certainly be much easier with threads opposed to processes; however, this is the current issue with the C++ codebase here that uses a functional decomposition instead of a proper object oriented design. I've attempted to refactor, but the change is nontrivial and has eaten quite a lot of my time as the C++ is not my code to begin with.

TensorFlow _can_ run in multiple processes, but you'll need an explicitly dedicated GPU for each process or else to just use the CPU. I use this config to train multiple models (independently) on a single node equipped with multiple GPUs using the linux tool `screen`. To share a policy, you'd need some form of synchronization mechanism between the processes. I've seen Redis used by OpenAI to handle this sort of issue in their [work](https://blog.openai.com/evolution-strategies/), though this is obviously for a massively parallel system running across hundreds of CPU cores. Alternatively, you can probably use TF callbacks and some form of mutex/semaphore.

Ultimately, I'd suggest a multi-processing approach as python threads are a rather limited form of parallelism. However, feel free to dig into the C++ to refactor out the poor data management and support threads! A change like that would likely solve the remaining bugs in this codebase, i.e., #36

**Comment by EliasHasle** [comment]
Thanks for your reply. It doesn't sound like something either of us should
really prioritize. I like SMB, but I don't have any good (non-nostagical)
reasons to prefer that environment to others that are similar in form and
complexity. :-)

Den man. 17. des. 2018, 23.17 skrev Christian Kauten <
notifications@github.com:

**Comment by Kautenja** [comment]
I feel the same way!

**Comment by Kautenja** [comment]
Parallelism of all forms is now supported by the master branch. Code will release under version 3.0.0 sometime today. Closing issue
