### ISSUE TITLE
Failed to install version 3.0.2 on Windows

### ISSUE THREAD

**Issue by EliasHasle** [Kautenja/nes-py#45]
### Describe the bug

Couldn't install newest version. Main error message is:
> AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'

### To Reproduce

In powershell (or other terminal, presumably):
> pip install --upgrade nes-py

### Expected behavior

Successful installation.

### Environment

-   Operating System: Windows 10 x64
-   Python version: 3.6.7
-   C++ compiler and version: **Don't know. I have Visual Studio 2017 (15.9.4) installed.**

### Additional context

> PS C:\Windows\system32> pip install --upgrade nes-py gym-super-mario-bros
> Collecting nes-py
>   Downloading https://files.pythonhosted.org/packages/fe/1b/6bffbcc167e9044bfdddb5d76b51bb76049d514d43865dc086e86f9a2c38/nes_py-3.0.2.tar.gz
> Collecting gym-super-mario-bros
>   Downloading https://files.pythonhosted.org/packages/fb/62/f2d469d5efc3b2eb94663f1dfb66e035a342935ed400c6745e90bf34b363/gym_super_mario_bros-6.0.2-py2.py3-none-any.whl (197kB)
>     100% |████████████████████████████████| 204kB 1.6MB/s
> Requirement already satisfied, skipping upgrade: gym>=0.10.9 in c:\users\elias\appdata\local\programs\python\python36\lib\site-packages (from nes-py) (0.10.9)
> Requirement already satisfied, skipping upgrade: matplotlib>=2.3.2 in c:\users\elias\appdata\local\programs\python\python36\lib\site-packages (from nes-py) (3.0.2)
> Requirement already satisfied, skipping upgrade: numpy>=1.12.1 in c:\users\elias\appdata\local\programs\python\python36\lib\site-packages (from nes-py) (1.15.4)
> Requirement already satisfied, skipping upgrade: opencv-python>=3.4.0.12 in c:\users\elias\appdata\local\programs\python\python36\lib\site-packages (from nes-py) (3.4.4.19)
> Requirement already satisfied, skipping upgrade: pygame>=1.9.3 in c:\users\elias\appdata\local\programs\python\python36\lib\site-packages (from nes-py) (1.9.4)
> Requirement already satisfied, skipping upgrade: pyglet>=1.3.2 in c:\users\elias\appdata\local\programs\python\python36\lib\site-packages (from nes-py) (1.3.2)
> Requirement already satisfied, skipping upgrade: tqdm>=4.19.5 in c:\users\elias\appdata\local\programs\python\python36\lib\site-packages (from nes-py) (4.28.1)
> Requirement already satisfied, skipping upgrade: scipy in c:\users\elias\appdata\local\programs\python\python36\lib\site-packages (from gym>=0.10.9->nes-py) (1.1.0)
> Requirement already satisfied, skipping upgrade: requests>=2.0 in c:\users\elias\appdata\local\programs\python\python36\lib\site-packages (from gym>=0.10.9->nes-py) (2.21.0)
> Requirement already satisfied, skipping upgrade: six in c:\users\elias\appdata\local\programs\python\python36\lib\site-packages (from gym>=0.10.9->nes-py) (1.12.0)
> Requirement already satisfied, skipping upgrade: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\elias\appdata\local\programs\python\python36\lib\site-packages (from matplotlib>=2.3.2->nes-py) (2.3.0)
> Requirement already satisfied, skipping upgrade: cycler>=0.10 in c:\users\elias\appdata\local\programs\python\python36\lib\site-packages (from matplotlib>=2.3.2->nes-py) (0.10.0)
> Requirement already satisfied, skipping upgrade: kiwisolver>=1.0.1 in c:\users\elias\appdata\local\programs\python\python36\lib\site-packages (from matplotlib>=2.3.2->nes-py) (1.0.1)
> Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in c:\users\elias\appdata\local\programs\python\python36\lib\site-packages (from matplotlib>=2.3.2->nes-py) (2.7.5)
> Requirement already satisfied, skipping upgrade: future in c:\users\elias\appdata\local\programs\python\python36\lib\site-packages (from pyglet>=1.3.2->nes-py) (0.17.1)
> Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in c:\users\elias\appdata\local\programs\python\python36\lib\site-packages (from requests>=2.0->gym>=0.10.9->nes-py) (2.8)
> Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in c:\users\elias\appdata\local\programs\python\python36\lib\site-packages (from requests>=2.0->gym>=0.10.9->nes-py) (1.24.1)
> Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in c:\users\elias\appdata\local\programs\python\python36\lib\site-packages (from requests>=2.0->gym>=0.10.9->nes-py) (3.0.4)
> Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\elias\appdata\local\programs\python\python36\lib\site-packages (from requests>=2.0->gym>=0.10.9->nes-py) (2018.11.29)
> Requirement already satisfied, skipping upgrade: setuptools in c:\users\elias\appdata\local\programs\python\python36\lib\site-packages (from kiwisolver>=1.0.1->matplotlib>=2.3.2->nes-py) (40.6.3)
> Building wheels for collected packages: nes-py
>   Running setup.py bdist_wheel for nes-py ... error
>   Complete output from command c:\users\elias\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\elias\\AppData\\Local\\Temp\\pip-install-g66d63b4\\nes-py\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\elias\AppData\Local\Temp\pip-wheel-hdd5qieu --python-tag cp36:
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build\lib.win-amd64-3.6
>   creating build\lib.win-amd64-3.6\nes_py
>   copying nes_py\nes_env.py -> build\lib.win-amd64-3.6\nes_py
>   copying nes_py\_image_viewer.py -> build\lib.win-amd64-3.6\nes_py
>   copying nes_py\__init__.py -> build\lib.win-amd64-3.6\nes_py
>   creating build\lib.win-amd64-3.6\nes_py\wrappers
>   copying nes_py\wrappers\binary_to_discrete_space_env.py -> build\lib.win-amd64-3.6\nes_py\wrappers
>   copying nes_py\wrappers\clip_reward_env.py -> build\lib.win-amd64-3.6\nes_py\wrappers
>   copying nes_py\wrappers\downsample_env.py -> build\lib.win-amd64-3.6\nes_py\wrappers
>   copying nes_py\wrappers\frame_stack_env.py -> build\lib.win-amd64-3.6\nes_py\wrappers
>   copying nes_py\wrappers\normalize_reward_env.py -> build\lib.win-amd64-3.6\nes_py\wrappers
>   copying nes_py\wrappers\penalize_death_env.py -> build\lib.win-amd64-3.6\nes_py\wrappers
>   copying nes_py\wrappers\reward_cache_env.py -> build\lib.win-amd64-3.6\nes_py\wrappers
>   copying nes_py\wrappers\__init__.py -> build\lib.win-amd64-3.6\nes_py\wrappers
>   creating build\lib.win-amd64-3.6\nes_py\_app
>   copying nes_py\_app\cli.py -> build\lib.win-amd64-3.6\nes_py\_app
>   copying nes_py\_app\play.py -> build\lib.win-amd64-3.6\nes_py\_app
>   copying nes_py\_app\play_human.py -> build\lib.win-amd64-3.6\nes_py\_app
>   copying nes_py\_app\__init__.py -> build\lib.win-amd64-3.6\nes_py\_app
>   creating build\lib.win-amd64-3.6\nes_py\wrappers\_util
>   copying nes_py\wrappers\_util\lazy_frames.py -> build\lib.win-amd64-3.6\nes_py\wrappers\_util
>   copying nes_py\wrappers\_util\__init__.py -> build\lib.win-amd64-3.6\nes_py\wrappers\_util
>   creating build\lib.win-amd64-3.6\nes_py\_app\visualize
>   copying nes_py\_app\visualize\realtime_plot.py -> build\lib.win-amd64-3.6\nes_py\_app\visualize
>   copying nes_py\_app\visualize\__init__.py -> build\lib.win-amd64-3.6\nes_py\_app\visualize
>   running build_ext
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "C:\Users\elias\AppData\Local\Temp\pip-install-g66d63b4\nes-py\setup.py", line 95, in <module>
>       cmdclass={'build_ext': BuildExt},
>     File "c:\users\elias\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 143, in setup
>       return distutils.core.setup(**attrs)
>     File "c:\users\elias\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
>       dist.run_commands()
>     File "c:\users\elias\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
>       self.run_command(cmd)
>     File "c:\users\elias\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
>       cmd_obj.run()
>     File "c:\users\elias\appdata\local\programs\python\python36\lib\site-packages\wheel\bdist_wheel.py", line 188, in run
>       self.run_command('build')
>     File "c:\users\elias\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
>       self.distribution.run_command(command)
>     File "c:\users\elias\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
>       cmd_obj.run()
>     File "c:\users\elias\appdata\local\programs\python\python36\lib\distutils\command\build.py", line 135, in run
>       self.run_command(cmd_name)
>     File "c:\users\elias\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
>       self.distribution.run_command(command)
>     File "c:\users\elias\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
>       cmd_obj.run()
>     File "c:\users\elias\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
>       _build_ext.run(self)
>     File "c:\users\elias\appdata\local\programs\python\python36\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
>       _build_ext.build_ext.run(self)
>     File "c:\users\elias\appdata\local\programs\python\python36\lib\distutils\command\build_ext.py", line 339, in run
>       self.build_extensions()
>     File "C:\Users\elias\AppData\Local\Temp\pip-install-g66d63b4\nes-py\setup.py", line 17, in build_extensions
>       self.compiler.compiler_so.remove("-Wstrict-prototypes")
>   AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'
> 
>   ----------------------------------------
>   Failed building wheel for nes-py
>   Running setup.py clean for nes-py
> Failed to build nes-py
> Installing collected packages: nes-py, gym-super-mario-bros
>   Found existing installation: nes-py 2.0.0
>     Uninstalling nes-py-2.0.0:
>       Successfully uninstalled nes-py-2.0.0
>   Running setup.py install for nes-py ... error
>     Complete output from command c:\users\elias\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\elias\\AppData\\Local\\Temp\\pip-install-g66d63b4\\nes-py\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\elias\AppData\Local\Temp\pip-record-4hvm2g7f\install-record.txt --single-version-externally-managed --compile:
>     running install
>     running build
>     running build_py
>     creating build
>     creating build\lib.win-amd64-3.6
>     creating build\lib.win-amd64-3.6\nes_py
>     copying nes_py\nes_env.py -> build\lib.win-amd64-3.6\nes_py
>     copying nes_py\_image_viewer.py -> build\lib.win-amd64-3.6\nes_py
>     copying nes_py\__init__.py -> build\lib.win-amd64-3.6\nes_py
>     creating build\lib.win-amd64-3.6\nes_py\wrappers
>     copying nes_py\wrappers\binary_to_discrete_space_env.py -> build\lib.win-amd64-3.6\nes_py\wrappers
>     copying nes_py\wrappers\clip_reward_env.py -> build\lib.win-amd64-3.6\nes_py\wrappers
>     copying nes_py\wrappers\downsample_env.py -> build\lib.win-amd64-3.6\nes_py\wrappers
>     copying nes_py\wrappers\frame_stack_env.py -> build\lib.win-amd64-3.6\nes_py\wrappers
>     copying nes_py\wrappers\normalize_reward_env.py -> build\lib.win-amd64-3.6\nes_py\wrappers
>     copying nes_py\wrappers\penalize_death_env.py -> build\lib.win-amd64-3.6\nes_py\wrappers
>     copying nes_py\wrappers\reward_cache_env.py -> build\lib.win-amd64-3.6\nes_py\wrappers
>     copying nes_py\wrappers\__init__.py -> build\lib.win-amd64-3.6\nes_py\wrappers
>     creating build\lib.win-amd64-3.6\nes_py\_app
>     copying nes_py\_app\cli.py -> build\lib.win-amd64-3.6\nes_py\_app
>     copying nes_py\_app\play.py -> build\lib.win-amd64-3.6\nes_py\_app
>     copying nes_py\_app\play_human.py -> build\lib.win-amd64-3.6\nes_py\_app
>     copying nes_py\_app\__init__.py -> build\lib.win-amd64-3.6\nes_py\_app
>     creating build\lib.win-amd64-3.6\nes_py\wrappers\_util
>     copying nes_py\wrappers\_util\lazy_frames.py -> build\lib.win-amd64-3.6\nes_py\wrappers\_util
>     copying nes_py\wrappers\_util\__init__.py -> build\lib.win-amd64-3.6\nes_py\wrappers\_util
>     creating build\lib.win-amd64-3.6\nes_py\_app\visualize
>     copying nes_py\_app\visualize\realtime_plot.py -> build\lib.win-amd64-3.6\nes_py\_app\visualize
>     copying nes_py\_app\visualize\__init__.py -> build\lib.win-amd64-3.6\nes_py\_app\visualize
>     running build_ext
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\elias\AppData\Local\Temp\pip-install-g66d63b4\nes-py\setup.py", line 95, in <module>
>         cmdclass={'build_ext': BuildExt},
>       File "c:\users\elias\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 143, in setup
>         return distutils.core.setup(**attrs)
>       File "c:\users\elias\appdata\local\programs\python\python36\lib\distutils\core.py", line 148, in setup
>         dist.run_commands()
>       File "c:\users\elias\appdata\local\programs\python\python36\lib\distutils\dist.py", line 955, in run_commands
>         self.run_command(cmd)
>       File "c:\users\elias\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "c:\users\elias\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
>         return orig.install.run(self)
>       File "c:\users\elias\appdata\local\programs\python\python36\lib\distutils\command\install.py", line 545, in run
>         self.run_command('build')
>       File "c:\users\elias\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "c:\users\elias\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "c:\users\elias\appdata\local\programs\python\python36\lib\distutils\command\build.py", line 135, in run
>         self.run_command(cmd_name)
>       File "c:\users\elias\appdata\local\programs\python\python36\lib\distutils\cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "c:\users\elias\appdata\local\programs\python\python36\lib\distutils\dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "c:\users\elias\appdata\local\programs\python\python36\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
>         _build_ext.run(self)
>       File "c:\users\elias\appdata\local\programs\python\python36\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
>         _build_ext.build_ext.run(self)
>       File "c:\users\elias\appdata\local\programs\python\python36\lib\distutils\command\build_ext.py", line 339, in run
>         self.build_extensions()
>       File "C:\Users\elias\AppData\Local\Temp\pip-install-g66d63b4\nes-py\setup.py", line 17, in build_extensions
>         self.compiler.compiler_so.remove("-Wstrict-prototypes")
>     AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'
> 
>     ----------------------------------------
>   Rolling back uninstall of nes-py
> Command "c:\users\elias\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\elias\\AppData\\Local\\Temp\\pip-install-g66d63b4\\nes-py\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\elias\AppData\Local\Temp\pip-record-4hvm2g7f\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\elias\AppData\Local\Temp\pip-install-g66d63b4\nes-py\

**Comment by Kautenja** [comment]
https://blog.travis-ci.com/2018-10-11-windows-early-release looks like travis did add windows support back in October. I'll get this worked in so Windows builds don't keep breaking. Maybe even get some Windows wheels published on PyPi to speedup the install process.

**Comment by Kautenja** [comment]
should be fixed in 3.0.3. Travis doesn't support Python / C++ projects for windows or MacOS so only Linux on the build server. Closing issue.
