### ISSUE TITLE
Install fails on OS X with Xcode 10 Command Line Tools

### ISSUE THREAD

**Issue by markedwards** [Kautenja/nes-py#57]
### Describe the bug

Installation fails on OS X with Xcode 10, due to stdlibc++ no longer supported.

### To Reproduce

1.  run `pip install nes-py` on OS X with Xcode 10 and no cruft present from prior Xcode installs

### Expected behavior

Install should succeed

### Environment

-   Operating System: OS X
-   Python version: 3.7.3
-   C++ compiler and version: clang++ 10.0.1

### Additional context

Error that occurs is:
```
    nes_py/nes/include/cartridge.hpp:12:10: fatal error: 'vector' file not found
    #include <vector>
             ^~~~~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1
```
This is similar to https://github.com/pandas-dev/pandas/pull/24274/files, and a similar solution could work.

I was able to get around the issue by doing:

```
MACOSX_DEPLOYMENT_TARGET=10.9 pip install nes-py
```

**Comment by Kautenja** [comment]
Let me see if I can get an emulated environment up and running that can duplicate the error and make sure the pandas solution will work here. Thanks for catching this issue and providing a solution!

**Comment by Kautenja** [comment]
I can't seem to replicate the issue on either my development machine or [build server](https://travis-ci.com/Kautenja/nes-py) both running MacOS 14.14.4 with Xcode 10.2.1 (also clang 10.0.1 and python 3.7.3). Which specific version of MacOS and Xcode caused this compilation failure?

It does appear that libstdc++ has been deprecated by Apple in favor of libc++ [[1](https://stackoverflow.com/questions/52679906/fatal-error-vector-file-not-found-with-xcode-10)]. It may be worth exploring the support for libc++ on Linux and Windows instead of building on deprecated MacOS toolkits.

**Comment by markedwards** [comment]
I am on OS X 10.14.4 with the CommandLineTools installed, not Xcode.  CommandLineTools version is  10.2.1.0.1.1554506761.

**Comment by zyansheep** [comment]
I found a fix for OS X 10.11 with CommandLineTools 9.2, but it should work for other versions.
Just add `'-stdlib=libc++'` in setup.py under `EXTRA_COMPILE_ARGS`
Then run `pip install -e .` in the repo folder

If you are getting `clang: error: invalid deployment target for -stdlib=libc++`
do `export MACOSX_DEPLOYMENT_TARGET=10.10`

**Comment by Kautenja** [comment]
I've switch compilers as g++ produces better results on Linux (although the results are the same on MacOS for both clang++ and g++). If the issue still happens, it might be worth updating setup.py with some MacOS specific logic for more seamless installation.

**Comment by krinkere** [comment]
Running `MACOSX_DEPLOYMENT_TARGET=10.9 pip install nes-py `worked for me

**Comment by Neqit** [comment]
OSX 10.13.6 
clang-1000.10.44.4

My solution, paste this 2 commands in the terminal:
1) MACOSX_DEPLOYMENT_TARGET=10.13
2) CFLAGS='-stdlib=libc++' pip install nes-py

macOS-deployment-target can be less then 10.13, but I'm not sure how much less

**Comment by Kautenja** [comment]
Closing issue as it seems stale and mostly environment-dependent.
