### ISSUE TITLE
Get OSError: exception: access violation reading memory When multithreading

### ISSUE THREAD

**Issue by lsnuwafi** [Kautenja/nes-py#64]
Got os access violation reading error when try to train my model use multi-threading.
When the program try to call the pyd.
I am using 64-win10, py3.7, and NES-PY 7.0.1
 File "D:\py37\lib\site-packages\nes_py\nes_env.py", line 259, in reset
    self._restore()
  File "D:\py37\lib\site-packages\nes_py\nes_env.py", line 221, in _restore
    _LIB.Restore(self._env)
OSError: exception: access violation reading 0x000001DFDBDC8E30

**Comment by Kautenja** [comment]
I need more information to reproduce the issue. Closing for now.
