### ISSUE TITLE
How to support ROM mapper number which is not supported now

### ISSUE THREAD

**Issue by 60999** [Kautenja/nes-py#73]
I have two ROM files that prompt separately“

ValueError: ROM has an unsupported mapper number 167. please see https://github.com/Kautenja/nes-py/issues/28 for more information”

and

“ValueError: ROM has an unsupported mapper number 241. please see https://github.com/Kautenja/nes-py/issues/28 for more information”

How can this simulator support these two ROMs? thank you,

The file can be downloaded here:

您有一份文件待查收！即刻点击链接获取文件：https://cowtransfer.com/s/6f07270f4b5f4a 或进入 cowtransfer.com 获取，在首页输入取件码：371565（24小时内有效）

or I can send E-mail to you. Thanks.

**Comment by Kautenja** [comment]
Hi, the mapper for these ROMs would need to be implemented to support these ROMs.

**Comment by ManPython** [comment]
I did not found any rom that can work
