### ISSUE TITLE
Is nes-py available in Anaconda environment?

### ISSUE THREAD

**Issue by KC900201** [Kautenja/nes-py#74]
I would like to know if users can install nes-py package in Anaconda environment?
For example conda install -c forge nes-py.

**Comment by Kautenja** [comment]
I only officially release nes-py to pypi (installed using pip) at the current time. I don't really use conda so I'm not really familiar with how the conda package manager works.

**Comment by Kautenja** [comment]
If it is not available, it can be installed by cloning and running `python setup.py install` from within the conda environment.
