### ISSUE TITLE
Access information not stored in RAM

### ISSUE THREAD

**Issue by pcountryman** [Kautenja/nes-py#75]
I was wondering if there was a way to access information that isn't stored in the RAM. In some games, information is stored outside of the RAM, but I cannot figure out how to use this emulator to access that information. Anytime I use self.ram[] to access anything greater than 0x0800, I get an error that the RAM is a numpy array of 2048 entries, related to the 2KB memory of the RAM for a NES. I want to pull information stored elsewhere (0x6000 for instance). Is there a way to do this that I am not familiar with? Thank you!
![NES_env_RAM_error](https://user-images.githubusercontent.com/65911278/118035410-2af2e000-b339-11eb-8282-bea930d297a0.png)

**Comment by Kautenja** [comment]
My understanding is that addresses above 0x6000 are reserved for access to the cartridge RAM. This could be implemented, but is not immediately available at this time. What is your use cases for reading from these addresses?
