### ISSUE TITLE
Can the simulator output audio info?

### ISSUE THREAD

**Issue by dave-yxw** [Kautenja/nes-py#76]
Dear Sir:

I found the image info from NESEnv. And also found the life/score etc at [gym-super-mario-bros](gym-super-mario-bros) project, but only on SuperMarioBros, not other nes games.
Now can I get the audio output in my py program?

**Comment by Kautenja** [comment]
Hi, the audio DSP kernel is not implemented at the current moment with no immediate plans to do so. It is doable, but challenging; feel free to fork if you'd like to implement the audio kernel!
