### ISSUE TITLE
Hold button

### ISSUE THREAD

**Issue by GoodLittleDev** [Kautenja/nes-py#82]
I am trying to figure out how the joypad wrapper handles holding a button as opposed to just repeat pressing. like if the same command is given twice does it hold or send the command twice and is there a way to tell it to hold the button down?

**Comment by Kautenja** [comment]
If the same command is given for consecutive frames, this would be considered a hold. For a button to be considered a press, there would have to be a command to engage the button then the next command would disengage it.

The sequence:

```
NOP -> A -> A
```

is a hold on the A button while the sequence

```
NOP -> A -> NOP
```

Is a press of the A button
