### ISSUE TITLE
ValueError: ROM header zero fill bytes are not zero.

### ISSUE THREAD

**Issue by luorq3** [Kautenja/nes-py#86]
I want to load a new rom by nes_py, but it raise this error. 

`ValueError: ROM header zero fill bytes are not zero.`

And I find it's from a few lines code:

```
 def _zero_fill(self):
        """Return the zero fill bytes at the end of the header."""
        return self.header[11:].sum()
```

Will there be any side effects if I just modify the source code to bypass this limitation ? 

THANKS !

**Comment by Kautenja** [comment]
This suggests your ROM file is improperly formatted.
